spreading regression bugs evenly

diff --git a/ami b/ami
--- a/ami
+++ b/ami
@@ -3,6 +3,7 @@
 export AMI_VERSION=0.1.0
 AMI="$0"
 
+# "de-soft-link"
 while [ -h "$AMI" ]; do
   ls=$(ls -ld "$AMI")
   link=$(expr "$ls" : '.*-> \(.*\)$')
@@ -18,32 +19,28 @@ export AMI
 export AMI_PROG=$(basename "$0")
 export AMI_MDIR=$(dirname "$AMI")
 
-# load config
-AMI_CONF="$AMI_MDIR/etc/ami"
-[ -f "$AMI_CONF" ] && . "$AMI_CONF" "$AMI_CONF" || { echo "$AMI_PROG: no $AMI_CONF config file found" >&2; exit 1; }
+# try hard to do the right thing[tm]
+[ "$AMI_MDIR" = "." ] && AMI_MDIR=$(pwd);
+[[ "$AMI_MDIR" =~ ^/ ]] || AMI_MDIR=$(cd "$AMI_MDIR" && pwd);
 
 # load library
 AMI_LIBF="$AMI_MDIR/lib/ami"
 [ -f "$AMI_LIBF" ] && . "$AMI_LIBF" "$AMI_LIBF" || { echo "$AMI_PROG: no $AMI_LIBF lib file found" >&2; exit 1; }
-
-# DEBUG(for now)
-export AMI_DBG=${AMI_DBG:-1}
-settings
-export -f settings
+# it loads config so in practice 'load lib ami' alone in cmds should be ok
 
 export AMI_CWD=$(pwd)
 # not sure about that...
-[ -n "$AMI_ROOT" ] && {
-	cd "$AMI_ROOT" || die 1 "cd $AMI_ROOT failure" ;
-	} || {
-	die 1 "AMI_ROOT not set" ;
-	}
+[ -n "$AMI_ROOT" ] || die "AMI_ROOT not set.";
+cd "$AMI_ROOT" || die "cd $AMI_ROOT failure.";
 
 # bail if nothing to do...
-[ $# -eq 0 ] && usage
+[ $# -eq 0 ] && usage;
 
 # main()
-[ $AMI_DBG -eq 1 ] && echo "## cmd: '$1' ##"
+settings
+debug "main() args: '$@'.";
+debug "main() cmd: '$1'.";
+#die;
 case $1 in
 	cmds)
 		cmds ;;
@@ -57,9 +54,6 @@ esac
 
 ret=$?
 
-[ $AMI_DBG -eq 1 ] && {
-	echo "## ar<$@>gs ##" ;
-	echo "## pw<$(pwd)>d ##" ;
-} || true
+debug "main() pwd '$(pwd)'.";
 
 exit $ret;
diff --git a/bin/aur b/bin/aur
--- a/bin/aur
+++ b/bin/aur
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-load etc ami
+load lib ami
 load etc aur # AUR_CMD
 load lib aur
 
@@ -9,7 +9,7 @@ function aur_get() {
 	[ -n "$1" ] || return;
 	local pkg=$1
 	local d="$AMI_AURD/$pkg"
-	mkdir -p $d && pushd $d 2>/dev/null 1>&2 || die 1 "aur_get() pushd $d failure";
+	mkdir -p $d && pushd $d 2>/dev/null 1>&2 || die "aur_get() pushd $d failure." 1;
 	[ -f $pkg.tar.gz ] && {
 		aur_ver $pkg ||	{
 		  popd 2>/dev/null 1>&2;
@@ -17,10 +17,10 @@ function aur_get() {
 		}
 	}
 	# crudely list current state
-	md5sum $pkg*.tar.gz* 2>/dev/null || echo "$pkg IS-not";
+	md5sum $pkg*.tar.gz* 2>/dev/null || msg "$pkg IS-not.";
 	[ -f $pkg.tar.gz ] && {
 		popd 2>/dev/null 1>&2;
-		die 1 "aur_get() $pkg UN-version-ABLE";
+		die "aur_get() $pkg UN-version-ABLE." 1;
 	} || $AUR_CMD $pkg;
 	[ -f $pkg.tar.gz ] && aur_ver $pkg;
 	popd 2>/dev/null 1>&2;
@@ -30,15 +30,16 @@ function aur_get() {
 
 # gets manu packagos
 function aur_gets() {
-	[ -z "$1" ] && aur_usage && return
+	[ -z "$1" ] && aur_usage;
 	for p in $*; do
 		aur_get $p
 	done
 }
 
 function aur_usage() {
-	echo "# '$AMI_PROG aur [get] <pkg>s' is default"
-	echo "Usage: $AMI_PROG aur [get] <pkg>"
+	msg "'$AMI_PROG aur [get] <pkg>s' is default.";
+	echo "Usage: $AMI_PROG aur [get] <pkg>";
+	exit 3;
 }
 
 # main()
diff --git a/bin/import b/bin/import
--- a/bin/import
+++ b/bin/import
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-load etc ami
+# load etc ami
 #settings
 load lib ami # runcmd...
 load lib $(basename $0)
@@ -11,16 +11,16 @@ load lib aur
 
 function import_aur() {
 	echo "via AUR";
-	echo "# AUR import being implemented, mostly 'aur get'ing it...";
+	msg "AUR import being implemented, mostly 'aur get'ing it...";
 	local b="p/$pkg/aur";
 	# be careful what we ask for (grep args in 'status git $pkg' may collide...
-	runcmd status git $pkg | grep -q "$b" && die 234 "# $b already present";
+	runcmd status git $pkg | grep -q "$b" && die "$b already present." 234;
 	# or -v or -all switch in status git...
 	runcmd aur get $pkg;
 	# always try to get teh latest...
 	local vers=($(aur_exists $pkg));
-	[ ${#vers[*]} -gt 0 ] || die 235 "# import_aur() nothing to do";
-	echo -e "# available versions (in modification)sic!(time order)\n";
+	[ ${#vers[*]} -gt 0 ] || die "import_aur() nothing to do." 235;
+	echo -e "# available versions (in modification)sic!(time order):\n";
 	for v in ${vers[@]}; do
 		[[ "$v" =~ .*/"$pkg-"([^/]*)".tar.gz" ]] && echo "${BASH_REMATCH[1]}";
 	done
@@ -30,19 +30,20 @@ function import_aur() {
 	# prolly insert "good order?" prompt here...
 	local tout=300
 	read -p "Press SPACE to continue. " -N 1 -s -t $tout ||
-	  die $? "TIMEOUT after $tout seconds.";
-	[ "$REPLY" = " " ] || die $? "Bye, then.";
+	  die "TIMEOUT after $tout seconds." $?;
+	[ "$REPLY" = " " ] || die "Bye, then." $?;
 	echo "Okidoki.";
 
-	cd $AMI_TEMP/imports/aur/ || die 1 "# cd temp import failure";
+	msg "(re-)generating GIT fast-import file for pkg($pkg) of repo(aur).";
+	cd $AMI_TEMP/imports/aur/ || die "cd temp import failure." 1;
 	rm -f $pkg-fast-import;
 	aur_fast_import $pkg ${vers[@]} > $pkg-fast-import;
 	# NOW
 	[ $? -eq 0 ] && {
-		echo "# Importing GIT fast-import file for pkg($pkg) of repo(aur)";
+		msg "Importing into GIT.";
 		# cd $AMI_GITD && cat "$impdir/$fi_file" | git fast-import --quiet --date-format=rfc2822;
 		export GIT_DIR="$AMI_GITD/.git"; cat "$pkg-fast-import" | git fast-import --quiet --date-format=rfc2822; } || {
-		echo "# KABLOOM!";
+		msg "KABLOOM!";
 	}
 
 	# clean-up?
@@ -51,33 +52,33 @@ function import_aur() {
 # NOT nice $pkg global...
 function import_svn() {
 	echo "via Arch Linux SVN"
-	echo "SVN import ALMOST really implemented, kabloom!"
+	msg "SVN import ALMOST really implemented, kabloom!"
 	local b="p/$pkg/arch"
-	runcmd status git $pkg | grep -q "$b" && die 234 "# $b already present"
+	runcmd status git $pkg | grep -q "$b" && die "$b already present." 234;
 	local repos=($(svn_exists $pkg))
 	# perhaps svn_get here too? hmmm...
 	[ "${#repos[*]}" -eq 0 ] && {
 		runcmd svn get $pkg
 	}
 	repos=($(svn_exists $pkg))
-	[ "${#repos[*]}" -eq 0 ] && die 235 "# it appears there is no $pkg package in Arch (${repos[@]})"
+	[ "${#repos[*]}" -eq 0 ] && die "it appears there is no $pkg package in Arch (${repos[@]})." 235;
 	# TODO?: find (if it exists) and import all of history besides present "location"
-	[ "${#repos[*]}" -gt 1 ] && die 236 "# $pkg exists in both repos (IM-possible!)"
+	[ "${#repos[*]}" -gt 1 ] && die "$pkg exists in both repos (IM-possible!)." 236;
 	# trash da place
 	local impdir=$AMI_TEMP/imports/svn/$pkg
-	mkdir -p $impdir && cd $impdir || die 1 "# cd $impdir failure"
+	mkdir -p $impdir && cd $impdir || die "cd $impdir failure." 1;
 	local fi_file="fast-import"
 	rm -f $fi_file
 	local log_file
 	for r in ${repos[@]}; do
 		log_file=$(svn_log $r $pkg)
 		[ -z "$log_file" ] && continue
-		echo "# (re-)generating GIT fast-import file for pkg($pkg) of repo($r)";
+		msg "(re-)generating GIT fast-import file for pkg($pkg) of repo(arch/$r).";
 		cat $log_file | svn_collect_log_to fast-import $r $pkg $fi_file
 	done
-	# echo "# Importing into GIT" >&2;
+	msg "Importing into GIT.";
 	[ ! -s "$fi_file" ] && {
-		echo "# empty $fi_file (impossible, but TRUE)";
+		msg "empty $fi_file (impossible, but TRUE).";
 		rm -f "$fi_file";
 	} || {
 		cd $AMI_GITD && cat "$impdir/$fi_file" | git fast-import --quiet --date-format=rfc2822;
@@ -103,8 +104,9 @@ function import() {
 }
 
 function import_usage() {
-	echo "# '$AMI_PROG import <pkg> aur' is default"
-	echo "Usage: $AMI_PROG import <pkg> [svn|aur]"
+	msg "'$AMI_PROG import <pkg> aur' is default.";
+	echo "Usage: $AMI_PROG import <pkg> [svn|aur]";
+	exit 3;
 }
 
 # main()
diff --git a/bin/svn b/bin/svn
--- a/bin/svn
+++ b/bin/svn
@@ -1,21 +1,21 @@
 #!/bin/bash
 
-load etc ami
-load etc init # SVN_
+load lib ami
+#load etc init # SVN_
 load lib svn
 
 function svn_get() {
 	local d="$AMI_SVND"
 	for r in $SVN_REPOS; do
 		[ -d "$d/$r/.svn" ] && {
-			echo "# $AMI_PROG svn get $r/$1";
+			msg "$AMI_PROG svn get $r/$1.";
 			cd "$d/$r" && svn update $1 ;
 		}
 	done
 }
 
 function svn_gets() {
-	[ -z "$1" ] && svn_usage && return
+	[ -z "$1" ] && svn_usage;
 	for p in $*; do
 		svn_get $p
 	done
@@ -26,7 +26,7 @@ function svn_gets() {
 # from "first" rev i.e. opposite to svn convention, >0: from "last")
 # default is to limit to 5 revisions
 function svn_print_log() {
-	[ -z "$1" ] && svn_usage && return
+	[ -z "$1" ] && svn_usage;
 	local pkg="$1"
 	local log_file
 	local repos=$(svn_exists $pkg)
@@ -36,7 +36,7 @@ function svn_print_log() {
 	}
 	# trash da place
 	local logdir=$AMI_TEMP/imports/svn/$pkg
-	mkdir -p $logdir && cd $logdir || die 1 "# cd $logdir failure"
+	mkdir -p $logdir && cd $logdir || die "cd $logdir failure." 1;
 	# TODO... more sophisticated i.e. KNOW current rev and adjust cache
 	for r in $repos; do
 		log_file=$(svn_log $r $pkg) # $rev...
@@ -44,7 +44,7 @@ function svn_print_log() {
 			[ -s "$log_file" ] && {
 				cat "$log_file" | svn_collect_log_to prnsomerevs ${2:-5};
 			} || {
-				echo "# $r/$pkg log_file($log_file) empty (hmmmm)" >&2;
+				errmsg "$r/$pkg log_file($log_file) empty (hmmmm).";
 			}
 		}
 	done
@@ -54,8 +54,9 @@ function svn_print_log() {
 }
 
 function svn_usage() {
-	echo "# '$AMI_PROG svn get <pkg>' is default"
-	echo "Usage: $AMI_PROG svn [get|log] <pkg>"
+	msg "'$AMI_PROG svn get <pkg>' is default.";
+	echo "Usage: $AMI_PROG svn [get|log] <pkg>";
+	exit 3;
 }
 
 # main()
